name: phys_ocean
channels:
    - conda-forge
dependencies:
    - python=3.6    # Python version 3.6
    - matplotlib    # 2D plotting library    
    - numpy         # N-d array and numerics
    - xarray        # N-d labeled array library
    - intake        # allows installation of datasets
    - intake-xarray #xarray plugin for intake
    - pyviz::datashader #needed for holoviews visualization
    - netcdf4       # Wrapper for netcdf4
    - holoviews
    - gsw